baseURL: ""
languageCode: "en-us"
pygmentsstyle: 'monokai'

defaultContentLanguage: "en"
languages:
  en:
    contentDir: "content/english"
    title: "Hugo Novela i18n Site"
    languageName: "en"
    weight: 1
    menu:
      main:
      - identifier: home
        name: Home
        title: homepage
        url: /
        weight: -100
      - identifier: about
        name: About
        title: about section
        url: /en/about/
        weight: -50
      - identifier: post
        name: Posts
        title: posts section
        url: /en/post/
        weight: -40
  pl:
    contentDir: "content/polish"
    title: "Blog Hugo Novela i18n"
    languageName: "pl"
    weight: 2
    menu:
      main:
      - identifier: home
        name: Główna
        title: Główna
        url: /pl/
        weight: -100
      - identifier: about
        name: O mnie
        title: O mnie
        url: /pl/about/
        weight: -50
      - identifier: post
        name: Posty
        title: posty
        url: /pl/post/
        weight: -40
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
