baseURL: "https://example.com"
languageCode: "en-us"
pygmentsstyle: 'monokai'
defaultContentLanguage: "en"
languages:
  en:
    contentDir: "content/english"
    title: "Hugo Novela i18n Site"
    languageName: "en"
    weight: 1
  pl:
    contentDir: "content/polish"
    title: "Blog Hugo Novela i18n"
    languageName: "pl"
    weight: 2
