name = "Hugo Novela"
license = "MIT"
licenselink = "https://github.com/karolkieglerski/hugo-theme-novela/blob/master/LICENSE"
description = "A Hugo port of the Novela theme by Narative"
homepage = "https://hugo-novela-karolkieglerski.netlify.com/"
tags = ["blog"]
features = ["dark mode", "grid view"]
min_version = "0.55.0"

[author]
    name = "Karol Kieglerski"
    homepage = "https://karolsomething.netlify.app/"

# If porting an existing theme
[original]
    name = "The New Dynamic"
    homepage = "https://www.thenewdynamic.com/"
    repo = "https://github.com/forestryio/novela-hugo-starter"
